<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Package with implementations for IEventBus, ICommandDispatcher with in-process implementations. Not to be used in a production environment.</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DDD.BuildingBlocks.Core\DDD.BuildingBlocks.Core.csproj" />
    <ProjectReference Include="..\DDD.BuildingBlocks.Hosting.Background\DDD.BuildingBlocks.Hosting.Background.csproj" />
  </ItemGroup>

</Project>
