CREATE TABLE [dbo].[EVENTS]
   (	[AGGREGATEID] UNIQUEIDENTIFIER NOT NULL,
	[DATA] VARBINARY(max) NOT NULL,
	[VERSION] INT NOT NULL,
	[TYPE] VARCHAR(500) NOT NULL,
	[CREATIONDATE] DATETIME NOT NULL
   ) ;

  CREATE TABLE [dbo].[AGGREGATES]
   (	[AGGREGATEID] UNIQUEIDENTIFIER NOT NULL,
	[TYPE] VARCHAR(255) NOT NULL,
	[VERSION] INT NOT NULL
   ) ;

  CREATE TABLE [dbo].[MAPPINGS]
   (	[AGGREGATEID] UNIQUEIDENTIFIER NOT NULL,
	[TYPE] VARCHAR(255) NOT NULL,
	[KEY] VARCHAR(500) NOT NULL
   ) ;


  CREATE TABLE [dbo].[OFFSET]
   (	[OFFSET] INT NOT NULL,
        [WORKERID] VARCHAR(255) NOT NULL
   ) ;

  CREATE TABLE [dbo].[SNAPSHOTS]
   (	[AGGREGATEID] UNIQUEIDENTIFIER NOT NULL,
	[VERSION] INT NOT NULL,
	[TYPE] VARCHAR(500) NOT NULL,
	[SERIALIZEDDATA] VARBINARY(max) NOT NULL
   ) ;


  CREATE TABLE [dbo].[UNIQUE_CONSTRAINTS]
   (	[AGGREGATETYPE] VARCHAR(255) NOT NULL,
	[AGGREGATEPROPERTY] VARCHAR(255) NOT NULL,
	[PROPERTYVALUE] VARCHAR(255) NOT NULL,
	[AGGREGATEID] UNIQUEIDENTIFIER NOT NULL
   ) ;


  ALTER TABLE [dbo].[EVENTS] ADD CONSTRAINT EVENTS_PK PRIMARY KEY (AGGREGATEID, VERSION);
  CREATE UNIQUE INDEX IX_EVENTS_AGGRID_VERSION ON [dbo].[EVENTS] (AGGREGATEID, VERSION);
  CREATE INDEX IX_EVENTS_AGGREGATEID ON [dbo].[EVENTS] (AGGREGATEID);

  CREATE UNIQUE INDEX UNIQUE_CONSTRAINTS_UK1 ON [dbo].[UNIQUE_CONSTRAINTS] (AGGREGATETYPE, AGGREGATEPROPERTY, PROPERTYVALUE);

  ALTER TABLE [dbo].[AGGREGATES] ADD CONSTRAINT AGGREGATES_PK PRIMARY KEY (AGGREGATEID);
  CREATE UNIQUE INDEX IX_AGGREGATEID ON [dbo].[AGGREGATES] (AGGREGATEID);


  ALTER TABLE [dbo].[MAPPINGS] ADD CONSTRAINT MAPPINGS_PK PRIMARY KEY (AGGREGATEID, TYPE);

  ALTER TABLE [dbo].[SNAPSHOTS] ADD CONSTRAINT PK_AGGREGATEID_VERSION PRIMARY KEY (AGGREGATEID, VERSION);
