<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Simple module system for Microsoft.Extensions.DependencyInjection.</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Hosting" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DDD.BuildingBlocks.Core\DDD.BuildingBlocks.Core.csproj" />
  </ItemGroup>

</Project>
