<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <Description>Package with implementations based on Azure.</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DDD.BuildingBlocks.Core\DDD.BuildingBlocks.Core.csproj" />
      <ProjectReference Include="..\DDD.BuildingBlocks.DI.Extensions\DDD.BuildingBlocks.DI.Extensions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Identity" />
      <PackageReference Include="Azure.Messaging.ServiceBus" />
      <PackageReference Include="Azure.Storage.Blobs" />
      <PackageReference Include="Microsoft.ApplicationInsights" />
    </ItemGroup>

</Project>
