<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>PostgreSQL event-store provider for DDD.BuildingBlocks.</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DDD.BuildingBlocks.Core\DDD.BuildingBlocks.Core.csproj" />
  </ItemGroup>

</Project>
